fix anchor and move scroll function in adopters js
EclipseFdn/solstice-assets pull request #207
Opened 2020-12-16 14:51 UTC by flora8984461

Fix https://github.com/EclipseFdn/eclipsefdn-project-adopters/issues/39

Signed-off-by: Yi Liu <yi.liu@eclipse-foundation.org>

2020-12-16 21:00 UTC, autumnfound requested changes
Have you included instructions for previewing content? Is it just running hugo, or do you need special setup?

2020-12-16 21:08 UTC, flora8984461 commented on docs/iot-adopters.html
> +        eclipseFdnAdopters.getWGList({src_root: "https://api.eclipse.org/adopters", working_group: "internet-things-iot", ul_classes: "text-center list-inline"})
Can I just use iot as an example, then in the <pre> to show we add other params?

2020-12-16 21:14 UTC, autumnfound commented on docs/iot-adopters.html
> +        eclipseFdnAdopters.getWGList({src_root: "https://api.eclipse.org/adopters", working_group: "internet-things-iot", ul_classes: "text-center list-inline"})
Nvm, this is fine as long as we scope it as a test page. Sludge brain, sorry

2020-12-17 14:06 UTC, autumnfound approved these changes

2020-12-18 19:57 UTC, autumnfound approved these changes

2020-12-18 21:20 UTC, merged